### ISSUE TITLE
cctyper dies with missing files

### ISSUE THREAD

**Issue by jnesme** [Russel88/CRISPRCasTyper#14]
Hi Jakob,

I was running cctyper (fresh conda install)  on a large fasta file (7.7GB) and it seems that it runs smoothly until minced step where it's trying to locate a missing file. Any idea on what might be the issue ?

Joseph.

```
cctyper -t 64 m64241e_210617_232502.hifi_reads.fasta cctyper.m64241e_210617_232502.hifi_reads.out
[2021-06-25 12:22:40] INFO: Running CRISPRCasTyper version 1.4.1
[2021-06-25 12:23:23] INFO: Predicting ORFs with prodigal
[2021-06-25 13:31:06] INFO: Running HMMER against Cas profiles
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 693/693 [13:06:04<00:00, 68.06s/it]
[2021-06-26 07:21:47] INFO: Parsing HMMER output
[2021-06-26 07:21:48] INFO: Subtyping putative operons
[2021-06-26 07:28:48] INFO: Predicting CRISPR arrays with minced
Traceback (most recent call last):
  File "/projects/codon_0000/apps/miniconda3/envs/cctyper/bin/cctyper", line 86, in <module>
    crispr_obj.run_minced()
  File "/projects/codon_0000/apps/miniconda3/envs/cctyper/lib/python3.9/site-packages/cctyper/minced.py", line 79, in run_minced
    self.write_spacers()
  File "/projects/codon_0000/apps/miniconda3/envs/cctyper/lib/python3.9/site-packages/cctyper/minced.py", line 156, in write_spacers
    f = open(self.out+'spacers/{}.fa'.format(crisp.crispr), 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'cctyper.m64241e_210617_232502.hifi_reads.out/spacers/m64241e_210617_232502/165939000/ccs_1.fa'

```

**Comment by Russel88** [comment]
Hi Joseph

That's odd. How does your fasta headers look like?

**Comment by jnesme** [comment]
They look like this, and that's probably these "/" that cause the issue, I'll try editing and run again :'(

```
>m64241e_210617_232502/20/ccs
>m64241e_210617_232502/6686011/ccs
>m64241e_210617_232502/14681679/ccs
>m64241e_210617_232502/22611689/ccs
>m64241e_210617_232502/30213142/ccs
>m64241e_210617_232502/37619981/ccs
>m64241e_210617_232502/45156585/ccs
>m64241e_210617_232502/52627283/ccs
>m64241e_210617_232502/60162622/ccs
>m64241e_210617_232502/67700160/ccs

```

**Comment by Russel88** [comment]
Yeah, definitely the '/' that are messing things up.

**Comment by zh8008** [comment]
I'm glad you like the tool! But I had some issues about minced
Traceback (most recent call last):
  File "/project/hz/.conda/envs/AcaFinder/bin/cctyper", line 91, in <module>
    crispr_obj.run_minced()
  File "/project/hz/.conda/envs/AcaFinder/lib/python3.8/site-packages/cctyper/minced.py", line 75, in run_minced
    subprocess.run(['minced',
  File "/project/hz/.conda/envs/AcaFinder/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/project/hz/.conda/envs/AcaFinder/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/project/hz/.conda/envs/AcaFinder/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'minced'

**Comment by zh8008** [comment]
I'm glad you like the tool! 
But I had some issues about minced.
`Traceback (most recent call last):
File "/project/hz/.conda/envs/AcaFinder/bin/cctyper", line 91, in
crispr_obj.run_minced()
File "/project/hz/.conda/envs/AcaFinder/lib/python3.8/site-packages/cctyper/minced.py", line 75, in run_minced
subprocess.run(['minced',
File "/project/hz/.conda/envs/AcaFinder/lib/python3.8/subprocess.py", line 493, in run
with Popen(*popenargs, **kwargs) as process:
File "/project/hz/.conda/envs/AcaFinder/lib/python3.8/subprocess.py", line 858, in init
self._execute_child(args, executable, preexec_fn, close_fds,
File "/project/hz/.conda/envs/AcaFinder/lib/python3.8/subprocess.py", line 1720, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'minced'`
