### ISSUE TITLE
Error when running cctyper: sed: cannot rename <output filename>/sed78a7GM: Permission denied

### ISSUE THREAD

**Issue by jdcfc** [Russel88/CRISPRCasTyper#35]
After running `INFO: Running HMMER against Cas profiles` , the job will instantly terminate and I receive the following error:

` sed: cannot rename <output filename>/sed78a7GM: Permission denied
Traceback (most recent call last):
  File "/opt/miniconda3/envs/cctyper/bin/cctyper", line 83, in <module>
    hmmeri.main_hmm()
  File "/opt/miniconda3/envs/cctyper/lib/python3.8/site-packages/cctyper/hmmer.py", line 26, in main_hmm
    self.load_hmm()
  File "/opt/miniconda3/envs/cctyper/lib/python3.8/site-packages/cctyper/hmmer.py", line 85, in load_hmm
    hmm_df = pd.read_csv(self.out+'hmmer.tab', sep='\s+', header=None,
  File "/opt/miniconda3/envs/cctyper/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/opt/miniconda3/envs/cctyper/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/opt/miniconda3/envs/cctyper/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/miniconda3/envs/cctyper/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/miniconda3/envs/cctyper/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/opt/miniconda3/envs/cctyper/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/opt/miniconda3/envs/cctyper/lib/python3.8/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '<output filename>/hmmer.tab' `

I was just wondering if anyone has come across this error and if so, how they resolved it?

Thanks in advance!

**Comment by Russel88** [comment]
Hi

I think it's because you have no matches to any of the HMMs. Is it a very short sequence? Does it work with other sequences?

**Comment by jdcfc** [comment]
Hi,

Thank you for your response. And thank you for making such a handy tool!

You're right! I was testing the software with a file that had very short sequences. When using a full genome, it worked just fine. Thanks again.
